name: "FUXA by Rocks"
description: "Web-based Process Visualization (SCADA/HMI/Dashboard) software"
version: "1.0.2"
url: "https://github.com/unocelli/SmartLiving-FUXA"
slug: "fuxa-slr"
webui: "http://[HOST]:[PORT:1881]/home"
panel_icon: mdi:dog
panel_title: FUXA
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:/usr/src/app/FUXA/server/_appdata:rw
  - addons:rw
  - config:/usr/src/app/FUXA/server/_appdata:rw
startup: services
ports:
  1881/tcp: 1881


