name: "FUXA by Rocks"
description: "Web-based Process Visualization (SCADA/HMI/Dashboard) software"
version: "1.0.1"
url: "https://github.com/unocelli/SmartLiving-FUXA"
slug: "fuxa-slr"
webui: "http://[HOST]:[PORT:1881]/home"
panel_icon: mdi:dog
panel_title: FUXA
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
  - addons:rw
  - config:rw
startup: services
volumes:
  - './appdata:/usr/src/app/FUXA/server/_appdata'
  - './db:/usr/src/app/FUXA/server/_db'
  - './logs:/usr/src/app/FUXA/server/_logs'
  - './images:/usr/src/app/FUXA/server/_images'
ports:
  1881/tcp: 1881


